#!/bin/bash

# one-time setup script to be downloaded and run directly,
# will do a deploy if already set up locally.

USER=drewwestphal
REPO=riverboard
URL="git@github.com:${USER}/${REPO}.git"

cd $HOME

if [ -d ./$REPO/.git ]; then
    git -C ./$REPO pull
else
    if [ -d ./$REPO ]; then
        # residual directory from non-git development, put to the side
        mv -f ./$REPO $(mktemp -d "./old.${REPO}.XXXX")
    fi

    # into the install directory $HOME/$REPO
    git clone $URL
fi

./$REPO/deploy
